databases:
  - name: financial-db
    plan: free
    databaseName: financial_db
    user: financial_user

services:
  - type: web
    name: financial-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api-docs
    envVars:
      - key: PGHOST
        fromDatabase:
          name: financial-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: financial-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: financial-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: financial-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: financial-db
          property: password
      - key: SERVER_PORT
        value: "9000"
