kind = "api"
previewPath = "/swagger-ui/index.html"
title = "Spring Boot API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 9000
name = "Spring Boot API"
paths = ["/api/v1", "/swagger-ui", "/api-docs", "/webjars"]

[services.development]
run = "java -jar /home/runner/workspace/backend/target/financial-system-0.0.1-SNAPSHOT.jar --server.port=9000"
